---
- name: Install Docker
  hosts: docker-servers,localhost
  become: yes
  become_method: sudo

  tasks:
  - name: install docker
    yum:
      name: docker
      state: latest

  - name: start docker service
    service:
      name: docker
      state: started
